### ISSUE TITLE
Regular Expressions for operator

### ISSUE THREAD

**Issue by yoshschulman** [newrelic/nr-entity-tag-sync#36]
### Feature Description
Use of RegEx for matching extEntityKey with entityKey

### Describe Alternatives
We find the provided operators are limited.  For instance if we want to find a match with the value that only ends with a phrase but does not start with a certain phrase we cannot.

### Additional context
We are also missing the ability to have compounded operators with AND or OR statements

**Comment by sdewitt-newrelic** [comment]
Hi @yoshschulman thanks for the request.  Could you provide a specific example for the regex use case?  In particular, what are you thinking the `match` element would look like in the configuration for such a use case?  In particular, is the ask to be able to be able to use a regex to find external entities and likewise for New Relic entities or is it to match the external entity key against an expression specified as the entityKey?  The difference between these two:

```
extEntityQuery:
    type: cmdb_ci_email_server
    ...
    regex: "specify a regex here to find matching external entities"
entityQuery:
    ...
    regex: "specify a regex here to find New Relic entities"
```

*OR*

```
match:
  extEntityKey: someKey
  match: matches
  entityKey: "specify a regex here and match the value of someKey against it"
```

With regards to compound operators, that is likely something we won't be able to do.
